### ISSUE TITLE
提示：Connection reset

### ISSUE THREAD

**Issue by Polaristime2026** [Jetereting/idea-activate#1]
![image](https://github.com/Jetereting/idea-activate/assets/11585188/49cf9dca-80a4-4fe8-b500-2907d603a418)

**Comment by Polaristime2026** [comment]
![image](https://github.com/Jetereting/idea-activate/assets/76163264/af4a1ea3-257a-494e-93ec-f85eb2fd0d18)

**Comment by Polaristime2026** [comment]
![image](https://github.com/Jetereting/idea-activate/assets/76163264/820d3b1e-22fe-48ae-aa8d-c8410e03e809)

**Comment by Jetereting** [comment]
包括 unknow host 一般都是网络问题，都可以通过设置或取消 idea 的 proxy 来解决

**Comment by Jetereting** [comment]
代理问题/
