### ISSUE TITLE
一直顯示這個錯誤 "请至少先运行过一次 idea!

### ISSUE THREAD

**Issue by Chou-Hua** [Jetereting/idea-activate#10]
一直顯示這個錯誤 "请至少先运行过一次 idea!" 但已經運行過好幾次了。 有辦法解決嗎?

**Comment by Jetereting** [comment]
加我下微信 jetereting 我看看

**Comment by Chou-Hua** [comment]
我沒微信 貼圖給你看看
![Screenshot_23](https://github.com/Jetereting/idea-activate/assets/47706288/2fb09c41-c389-4cc5-b84e-4955b5492b9d)

**Comment by Jetereting** [comment]
请问是什么操作系统，如果是windows 打开 $APPDATA/JetBrains 然后看看里面都有哪些
如果是mac 打开 /Users/[用户名]/Library/Application Support/JetBrains 然后看看里面都有哪些

**Comment by Chou-Hua** [comment]
![image](https://github.com/Jetereting/idea-activate/assets/47706288/d39ca35c-0a8b-4b91-a42d-0ed302706357)
windows系統 idea版本:2019.3

**Comment by ybdt** [comment]
2019.3我那个方式就可以啊，https://github.com/ybdt/dev-hub/tree/main/如何放心的白嫖四大主流语言IDE

**Comment by Jetereting** [comment]
> ![image](https://private-user-images.githubusercontent.com/47706288/320491736-d39ca35c-0a8b-4b91-a42d-0ed302706357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODMwMTgsIm5iZiI6MTcxMjU4MjcxOCwicGF0aCI6Ii80NzcwNjI4OC8zMjA0OTE3MzYtZDM5Y2EzNWMtMGE4Yi00YjkxLWE0MmQtMGVkMzAyNzA2MzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEzMjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMGNjNDc2MWIwOTAwYzEwOGI2NGYzODNkNWI3Mzk0YTg3YmU5ZmNjZjg1OGI2NjUyYTAxMmFiZjI1ZGI2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dUkm1-T6Qiu0qOsUbYB6sBLzEtf3_whpr3pLU50DfME) windows系統 idea版本:2019.3

可以尝试下更新到最新版本，很老版本的目录结构不一样了

**Comment by Chou-Hua** [comment]
好吧.. 新版的用的很不習慣就是了

**Comment by Jetereting** [comment]
![image](https://github.com/Jetereting/idea-activate/assets/11585188/d3629308-48fd-4445-8316-e6d0146a3da8)
新版可以自由选择新老布局

**Comment by Jetereting** [comment]
从 v2.0.6 开始 支持2019类似的老版本了
