### ISSUE TITLE
激活了三天是什么鬼

### ISSUE THREAD

**Issue by yyw-code** [Jetereting/idea-activate#3]
<img width="848" alt="image" src="https://github.com/Jetereting/idea-activate/assets/53207409/b6518b8a-248a-4b0e-86ff-e7526987987a">

**Comment by Jetereting** [comment]
<img width="925" alt="image" src="https://github.com/Jetereting/idea-activate/assets/11585188/424013c1-8096-49d9-8df3-97c255edfc4f">

点激活后出现的到期日期不用理会，会自动更新，以步骤三查询的为准
<img width="315" alt="image" src="https://github.com/Jetereting/idea-activate/assets/11585188/34c01c11-d0a0-4e7a-b149-21935c1b4be7">
