### ISSUE TITLE
https://idea.jeter.eu.org/  网页打不开

### ISSUE THREAD

**Issue by xiexuejian** [Jetereting/idea-activate#5]
用了半个月，现在激活不了，网页也打不开，是跑路了吗？

**Comment by Jetereting** [comment]
> 用了半个月，现在激活不了，网页也打不开，是跑路了吗？

需要挂代理了

**Comment by xiexuejian** [comment]
梯子？还是怎么操作？

**Comment by Jetereting** [comment]
> 梯子？还是怎么操作？

对 梯子，然后在idea 设置proxy

**Comment by Jetereting** [comment]
或者把 https 换成 http 也可以，http://idea.jeter.eu.org
